#!/bin/bash
# Auto-generate .env file from environment variables
# Usage:
#   ENVIRONMENT=dev DB_PASS=xxx API_KEY_LIST=key1,key2 \
#   LINE_CLIENT_ID=your_line_client_id \
#   LINE_CLIENT_SECRET=your_line_client_secret \
#   DISCORD_WEBHOOK_URL=your_discord_webhook_url \
#   ./setup-env.sh
#
# Note: LINE_REDIRECT_URI 已棄用，現在由前端在 API 請求中提供

set -e

# Required parameters
ENVIRONMENT=${ENVIRONMENT:-prod}
DB_PASS=${DB_PASS:?ERROR: DB_PASS is required}
API_KEY_LIST=${API_KEY_LIST:-}

# Line Login parameters
LINE_CLIENT_ID=${LINE_CLIENT_ID:-""}
LINE_CLIENT_SECRET=${LINE_CLIENT_SECRET:-""}

# LINE_REDIRECT_URI (DEPRECATED: 現在由前端在 /line/authorize 請求中提供)
# 保留此設定以向下相容，但新的實作不再使用環境變數中的值
LINE_REDIRECT_URI=${LINE_REDIRECT_URI:-""}

# Discord Webhook parameters
DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-""}

# Database settings
DB_USER="guangfu"
DB_HOST="postgres"
DB_PORT="5432"
DB_NAME="guangfu"
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Create .env file
cat > .env <<EOF
# ============================================================================
# Environment Variables (Auto-generated by CI/CD)
# ============================================================================
# Generated at: ${TIMESTAMP}
# Environment: ${ENVIRONMENT}
# DO NOT EDIT MANUALLY - Changes will be overwritten on next deployment
# ============================================================================

# ----------------------------------------------------------------------------
# Application Settings
# ----------------------------------------------------------------------------
ENVIRONMENT=${ENVIRONMENT}
APP_TITLE=花蓮光復救災平台 API
PORT=8080

# API Keys (from secrets)
ALLOW_MODIFY_API_KEY_LIST=${API_KEY_LIST}

# Server URLs
PROD_SERVER_URL=https://api.gf250923.org
DEV_SERVER_URL=https://uat-api.gf250923.org

# ----------------------------------------------------------------------------
# Database Settings (PostgreSQL)
# ----------------------------------------------------------------------------
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=${DB_NAME}

DB_USER=${DB_USER}
DB_PASS=${DB_PASS}
DB_NAME=${DB_NAME}

# Database connection URL (auto-generated)
DATABASE_URL=${DATABASE_URL}

# ----------------------------------------------------------------------------
# LINE Login Settings
# ----------------------------------------------------------------------------
# ⚠️  DEPRECATED: LINE_REDIRECT_URI 現在由前端在 /line/authorize 請求中提供
# 保留此設定以向下相容，但新的實作不再使用此環境變數
LINE_CLIENT_ID=${LINE_CLIENT_ID}
LINE_CLIENT_SECRET=${LINE_CLIENT_SECRET}
LINE_REDIRECT_URI=${LINE_REDIRECT_URI}

# ----------------------------------------------------------------------------
# Discord Webhook Settings
# ----------------------------------------------------------------------------
DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
EOF

# Verify .env file was created
if [ ! -s .env ]; then
  echo "ERROR: .env file is empty or was not created"
  exit 1
fi

echo "✓ Environment file created for ${ENVIRONMENT}"
echo "✓ File size: $(wc -c < .env) bytes"
echo "✓ Non-comment lines: $(grep -c '^[^#]' .env || echo 0)"
