"""init

Revision ID: 0f01908e6629
Revises: 
Create Date: 2025-10-08 14:01:03.033294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f01908e6629'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('township', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('has_vacancy', sa.String(), nullable=False),
    sa.Column('available_period', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('pricing', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('restrictions', sa.String(), nullable=True),
    sa.Column('room_info', sa.String(), nullable=True),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('info_source', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('registration_method', sa.String(), nullable=True),
    sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distance_to_disaster_area', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('org', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('role_type', sa.String(), nullable=False),
    sa.Column('headcount_need', sa.Integer(), nullable=False),
    sa.Column('headcount_got', sa.Integer(), nullable=False),
    sa.Column('role_status', sa.String(), nullable=False),
    sa.Column('has_medical', sa.Boolean(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=False),
    sa.Column('language_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headcount_unit', sa.String(), nullable=True),
    sa.Column('shift_start_ts', sa.BigInteger(), nullable=True),
    sa.Column('shift_end_ts', sa.BigInteger(), nullable=True),
    sa.Column('shift_notes', sa.Text(), nullable=True),
    sa.Column('assignment_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('assignment_count', sa.Integer(), nullable=True),
    sa.Column('assignment_notes', sa.Text(), nullable=True),
    sa.Column('pii_date', sa.BigInteger(), nullable=False),
    sa.Column('valid_pin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('station_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('detailed_address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('operating_hours', sa.String(), nullable=True),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medical_staff', sa.Integer(), nullable=True),
    sa.Column('daily_capacity', sa.Integer(), nullable=True),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('affiliated_organization', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mental_health_resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('duration_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service_format', sa.String(), nullable=False),
    sa.Column('service_hours', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('emergency_support', sa.Boolean(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('specialties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('waiting_time', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restrooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('facility_type', sa.String(), nullable=False),
    sa.Column('opening_hours', sa.String(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('has_water', sa.Boolean(), nullable=False),
    sa.Column('has_lighting', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('male_units', sa.Integer(), nullable=True),
    sa.Column('female_units', sa.Integer(), nullable=True),
    sa.Column('unisex_units', sa.Integer(), nullable=True),
    sa.Column('accessible_units', sa.Integer(), nullable=True),
    sa.Column('cleanliness', sa.String(), nullable=True),
    sa.Column('last_cleaned', sa.BigInteger(), nullable=True),
    sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distance_to_disaster_area', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('info_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shelters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_occupancy', sa.Integer(), nullable=True),
    sa.Column('available_spaces', sa.Integer(), nullable=True),
    sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opening_hours', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shower_stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('facility_type', sa.String(), nullable=False),
    sa.Column('time_slots', sa.String(), nullable=False),
    sa.Column('available_period', sa.String(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requires_appointment', sa.Boolean(), nullable=False),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('gender_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('pricing', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('info_source', sa.String(), nullable=True),
    sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distance_to_guangfu', sa.String(), nullable=True),
    sa.Column('contact_method', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pii_date', sa.BigInteger(), nullable=False),
    sa.Column('valid_pin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('registration_status', sa.String(), nullable=True),
    sa.Column('organization_nature', sa.String(), nullable=True),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('coordinator', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('registration_method', sa.String(), nullable=True),
    sa.Column('service_content', sa.Text(), nullable=True),
    sa.Column('meeting_info', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_refill_stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('water_type', sa.String(), nullable=False),
    sa.Column('opening_hours', sa.String(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('accessibility', sa.Boolean(), nullable=False),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('container_required', sa.String(), nullable=True),
    sa.Column('daily_capacity', sa.Integer(), nullable=True),
    sa.Column('water_quality', sa.String(), nullable=True),
    sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distance_to_disaster_area', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('info_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supply_id', sa.String(), nullable=False),
    sa.Column('total_number', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('received_count', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply_items')
    op.drop_table('water_refill_stations')
    op.drop_table('volunteer_organizations')
    op.drop_table('supplies')
    op.drop_table('shower_stations')
    op.drop_table('shelters')
    op.drop_table('restrooms')
    op.drop_table('reports')
    op.drop_table('mental_health_resources')
    op.drop_table('medical_stations')
    op.drop_table('human_resources')
    op.drop_table('accommodations')
    # ### end Alembic commands ###
