const teamMembers = [
  {
    id: 1,
    groupName: '網站更新組',
    personNames: [
      '王◯恆',
      'Sam',
      'Zack',
      'JessZhong',
      'audery1011',
      'Pink Li',
      '施宇',
      'ppqq',
      '強森',
      'Yukay ',
      '破破popo',
      '彭◯珍',
      'WilliamTai',
      '陳◯妏',
      'Abby Su',
      'Wenny Chang',
      'Yi',
      '謝◯雯',
      'Stephanie Sung',
      'Sucre Lin 林糖糖',
      'IKEA',
      'jerry._.',
      'Randy',
      'cy.hsu',
      'Sylvia Kuo',
      '陳◯柔',
      'JeanLu',
      'BensonTW',
      'ZhuMon',
      'Arey',
      'Ava Tu',
      'Mizhon',
      'Pichu',
      'haoyun, shih',
      '蘇◯育',
      'Glori',
      'Lindsay',
      'Meeka',
      'Oswald',
      'DanLin',
      'Chi',
      'Carol 朱◯綾',
      '浩富',
      'Leon CP',
      'Doris',
      'Patty Wei',
      '布魯明',
      'Peli',
      '蔡宇婕',
    ],
  },
  {
    id: 2,
    groupName: '地圖組',
    personNames: [
      'Zack',
      'Fannie',
      '張◯瑜',
      '雅',
      'Zeli',
      '曾◯容 (鷹)',
      'Claire',
      'ShunFa Yang',
      '嵐',
      'billy',
      'Annie Chen',
      '布魯明',
      'Hermes_DOG',
      '+1',
      'Eva Tseng',
    ],
  },
  {
    id: 3,
    groupName: '核實組',
    personNames: ['雅', '嵐', '小路', 'Basil'],
  },
  {
    id: 4,
    groupName: 'DC管理組',
    personNames: ['JessZhong', 'Sunny Yang', '瑜瑜', 'Tobie 偷偷', 'Andrew Yen', 'Chun Caroline'],
  },
  {
    id: 5,
    groupName: '宣傳組',
    personNames: [
      '于涵',
      'Sunny Yang',
      '捲捲 FANG JOU',
      '小魏 WEI',
      'ヨウヨウ',
      'Julia(小孟)',
      '阿一',
      '陳緯修(阿修)',
      'Shirley',
      'Clark Chen',
    ],
  },
  {
    id: 6,
    groupName: '設計組',
    personNames: [
      'Vita',
      'Sunny Yang',
      '葉◯均 Andy',
      'JessZhong',
      '瑜瑜',
      'Pichu',
      'Yuling',
      '渺渺',
      'Sucre Lin 林糖糖',
      'Doublewen',
      'Annie Chen',
      '企鵝',
      'Uta',
    ],
  },
  {
    id: 7,
    groupName: '廣宣組',
    personNames: ['Sunny Yang', 'Jocelyn', 'Yukay', 'Andrew Yen', 'Julia (小孟)', '陳緯修(阿修)'],
  },
  {
    id: 8,
    groupName: 'Line社群組 & 官方組',
    personNames: ['于涵', '施宇 (鯊魚)', 'Clark Chen', '+1'],
    additionGroups: [
      {
        groupTitle: 'Eslitec 以力股份有限公司',
        groupMembers: [
          '徐郁涵',
          '劉若珊',
          '潘綾緹',
          '曾子庭',
          '高銘聰',
          '黃子恩',
          '吳敏瑄',
          '陳頴姿',
          '徐誥謙',
        ],
      },
    ],
  },
  {
    id: 9,
    groupName: '公關組',
    personNames: ['捲捲 FANG JOU', 'Andrew Yen'],
  },
  {
    id: 10,
    groupName: '影片組',
    personNames: ['貝卡', '孟謙', 'longentry'],
  },
  {
    id: 11,
    groupName: '海巡組',
    personNames: ['Janet', '嵐', '小路', '艾瑪', 'DanLin', '出包'],
  },
  {
    id: 12,
    groupName: '進度管理組',
    personNames: ['Sucre Lin 林糖糖', 'Aylin', '陳怡妘'],
  },
  {
    id: 13,
    groupName: '企劃組',
    personNames: ['Doublewen', 'EmberWolfstar', 'Pichu'],
  },
];

const onSiteVolunteers = [
  '瀞瀞',
  '站前蜂窩創始-彥',
  'Fannie',
  '郡翔室內裝修有限公司',
  'Ting',
  'Amy Chang',
  '津J. LumenFord',
  'Tabo',
  '610',
  '巴尚小吉普',
  '小草的啦',
  'Uu-資訊傳遞',
  'Roco',
  'Ben',
  '志偉',
  '徐喇喇',
  'LCD - Lala',
  '富昌廣告',
  '呂浩丞',
  '劉凱文',
];

export { teamMembers, onSiteVolunteers };
